---
title: "About this site"
description: |
  Some additional details about the website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(readr)
library(dplyr)
library(ggplot2)
library(janitor)
library(lubridate)
library(visdat)
library(corrplot)
library(tidyr)


precipitation <- read_csv("data/hardvard_dataverse_tropidry/Daily_Precipitation_2013_to_2016.csv") %>% 
  clean_names() %>% 
  slice(-1) %>% 
  mutate(date = ymd(date),
         do_y = as.numeric(do_y),
         precip = as.numeric(precip))

biomet <- read_csv("data/hardvard_dataverse_tropidry/Micrometeorological_Biomet_Parameters_2013_to_2016.csv") %>% 
  clean_names() %>% 
  slice(-1) %>% 
  mutate(date = ymd_hm(date)) %>% 
  mutate(across(where(is.character), as.numeric))

monthly_gpp <- read_csv("data/hardvard_dataverse_tropidry/Monthly_NEE_GPP_Reco_2013_to_2016.csv") %>% 
  clean_names() %>% 
  slice(-1) %>% 
  unite(col = date, year, month, sep = "-") %>% 
  mutate(date = paste0(date, "-1"),
         date = ymd(date)) %>% 
  select(-date_1, -date_2) %>% 
  mutate(across(where(is.character), as.numeric))

ndvi_moha <- readxl::read_xlsx("data/hardvard_dataverse_tropidry/final -NDVI- smoothed -complete.xlsx") %>% 
  clean_names()
```


## Precipitation

```{r}
precipitation %>% 
  mutate(year_mon = zoo::as.yearmon(date)) %>% 
  group_by(year_mon) %>% 
  summarize(
    total_precip = sum(precip, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = as.factor(year_mon), y = total_precip)) +
  geom_bar(stat = "identity") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90, h = 1)) +
  labs(x = "Date", y = "Total precipitation per month (mm)")

### Agrupando los meses
precipitation %>%
  mutate(year_mon = zoo::as.yearmon(date)) %>%
  filter(year(date) < 2017) %>% 
  group_by(year_mon) %>%
  summarize(
    total_precip = sum(precip, na.rm = TRUE)
  ) %>%
  mutate(year = year(year_mon),
         month = month(year_mon, label = TRUE)) %>%
  # mutate(year_mon = as.character(year_mon)) %>%
  ggplot(aes(x = as.factor(month), y = total_precip, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_light(base_size = 12) +
  scale_y_continuous(breaks = seq(0, 450, by = 50)) +
  scale_fill_viridis_d() +
  labs(x = "Date", y = "Total precipitation per month (mm)",
       fill = "Year")
```

## Environmental drivers

```{r}
biomet %>% 
  mutate(year_mon = zoo::as.yearmon(date)) %>%
  filter(vpd > 0) %>% 
  ggplot(aes(x = as.factor(year_mon), y = vpd, fill = as.factor(year_mon))) +
  stat_boxplot(geom = "errorbar", width = 0.25) +
  geom_boxplot() +
  scale_y_continuous(breaks = seq(-10, 40, by = 5)) +
  scale_fill_viridis_d() +
  theme_light(base_size = 12) +
  theme(axis.text.x = element_text(angle = 90, h = 1)) +
  guides(fill = "none") +
  labs(x = "Date", y = "Vapor presurre deficit (hPa)")
```


```{r}
biomet %>% 
  mutate(year_mon = zoo::as.yearmon(date)) %>%
  # filter(vpd > 0) %>% 
  ggplot(aes(x = as.factor(year_mon), y = tair, fill = as.factor(year_mon))) +
  stat_boxplot(geom = "errorbar", width = 0.25) +
  geom_boxplot() +
  scale_y_continuous(breaks = seq(15, 38, by = 2)) +
  scale_fill_viridis_d() +
  theme_light(base_size = 12) +
  theme(axis.text.x = element_text(angle = 90, h = 1)) +
  guides(fill = "none") +
  labs(x = "Date", y = "Air temperature (C)")
```


```{r}
biomet %>% 
  mutate(year_mon = zoo::as.yearmon(date)) %>%
  filter(le > 0) %>%
  ggplot(aes(x = as.factor(year_mon), y = le, fill = as.factor(year_mon))) +
  stat_boxplot(geom = "errorbar", width = 0.25) +
  geom_boxplot() +
  # scale_y_continuous(breaks = seq(15, 38, by = 2)) +
  scale_fill_viridis_d() +
  theme_light(base_size = 12) +
  theme(axis.text.x = element_text(angle = 90, h = 1)) +
  guides(fill = "none") +
  labs(x = "Date", y = "Latent Heat (Wm-2)")
```


```{r}
biomet %>% 
  mutate(year_mon = zoo::as.yearmon(date)) %>%
  # filter(le > 0) %>%
  ggplot(aes(x = as.factor(year_mon), y = r_h, fill = as.factor(year_mon))) +
  stat_boxplot(geom = "errorbar", width = 0.25) +
  geom_boxplot() +
  # scale_y_continuous(breaks = seq(15, 38, by = 2)) +
  scale_fill_viridis_d() +
  theme_light(base_size = 12) +
  theme(axis.text.x = element_text(angle = 90, h = 1)) +
  guides(fill = "none") +
  labs(x = "Date", y = "Relative Humidity (%)")
```

## NDVI

```{r}
ndvi_moha %>% 
  mutate(date = ymd(date)) %>% 
  filter(year(date) < 2017) %>% 
  ggplot(aes(x = date, y = ndvi)) +
  # geom_point(alpha = 0.5, color = "#FF3A1D", size = 3) +
  geom_jitter(alpha = 0.5, color = "#FF3A1D", size = 2.5) +
  theme_linedraw() +
  scale_x_date(date_labels = "%b%Y", breaks = "months") +
  theme(axis.text.x = element_text(angle = 90, h = 1))
```

## Monthly GPP

```{r}
monthly_gpp %>% 
  ggplot(aes(x = date, y = average_gpp, group = 1)) +
  geom_errorbar(aes(ymin = average_gpp - gpp_stdev,
                    ymax = average_gpp + gpp_stdev),
                colour = "#4D4D4D", width = .4) +
  geom_line(linetype = 2) +
  geom_point(color = "#FF3A1D", size = 3.5) +
  theme_linedraw() +
  scale_x_date(date_labels = "%b%Y", breaks = "months") +
  theme(axis.text.x = element_text(angle = 90, h = 1)) +
  labs(x = "Date", y = "GPP (mgm-2s-1)")
```


## Relation between NDVI and GPP

```{r}
ndvi_summarized <- ndvi_moha %>% 
  mutate(year_mon = zoo::as.yearmon(date)) %>% 
  group_by(year_mon) %>% 
  summarize(
    ndvi_mean = mean(ndvi, na.rm = TRUE),
    ndvi_sd = sd(ndvi, na.rm = TRUE)
  )

gpp_ndvi <- monthly_gpp %>% 
  mutate(year_mon = zoo::as.yearmon(date)) %>% 
  inner_join(ndvi_summarized) 

gpp_ndvi %>% 
  ggplot(aes(x = average_gpp, y = ndvi_mean)) +
  geom_point(color = "#FF3A1D", size = 3.5) +
  theme_linedraw() +
  geom_smooth(method = "lm")

## Puedo sacar la regresión lineal entre gpp y ndvi y con esta sacar los
## distintos valores de gpp para cada día por ejemplo.

model <- lm(average_gpp ~ ndvi_mean, data = gpp_ndvi)
summary(model)
```

